version: 0.2

phases:
  install:
    commands:
      - echo "Install phase: no dependencies needed"
  build:
    commands:
      - echo "Granting execution permission to deployment script"
      - chmod +x scripts/restart_httpd.sh

artifacts:
  files:
    - '**/*'
    - '!README.md'
    - '!**/.gitignore'
